### ISSUE TITLE
CGG2015: Polish voter sending U.S. template

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/mbc-transactional-email#28]
Using TorGuard, I voted for CGG as a user in Poland. (Screenshot below)

![screen shot 2015-11-19 at 6 02 12 pm](https://cloud.githubusercontent.com/assets/8696853/11287286/714a98c0-8ee8-11e5-966c-fc824bac112b.png)

I was sent a U.S. transactional template: I tagged the content in the preview line, see the "US". (Screenshot below)

![screen shot 2015-11-19 at 6 03 16 pm](https://cloud.githubusercontent.com/assets/8696853/11287299/852c28ea-8ee8-11e5-874a-e0c05c54c69a.png)

Also, the template I was sent is different than the template in MailChimp and Mandrill. Notice how we say "Our millions of members" instead of using *|MEMBER_COUNT|*. (Screenshot below)

![screen shot 2015-11-19 at 6 06 23 pm](https://cloud.githubusercontent.com/assets/8696853/11287331/b0c65f2a-8ee8-11e5-91ea-d40116ac06fb.png)

Here is the template I was supposed to receive: 

![screen shot 2015-11-19 at 6 03 00 pm](https://cloud.githubusercontent.com/assets/8696853/11287340/bff57cf6-8ee8-11e5-9f41-48dee9a11e36.png)

**Comment by ArielSD** [comment]
@DeeZone Tagging you here since I can't assign. Please let me know if I can clarify anything!

**Comment by DeeZone** [comment]
Try `?country_code=PL` from the voting app.
