### ISSUE TITLE
CGG2015: Wrong U.S. Transactional Sent

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/mbc-transactional-email#30]
As a U.S. user, I was sent a transactional tagged as U.S.; it seems like it's the wrong template.

This is the template I was sent:
![screen shot 2015-11-19 at 6 25 47 pm](https://cloud.githubusercontent.com/assets/8696853/11304588/ba5a4d24-8f76-11e5-92ec-5a3f146a20a8.png)

This is the template I should have been sent:
![screen shot 2015-11-19 at 6 25 33 pm](https://cloud.githubusercontent.com/assets/8696853/11304594/c28e0b70-8f76-11e5-8949-242c9be80fc9.png)

@DeeZone

**Comment by DeeZone** [comment]
Clarified as not an issue through testing today.
