### ISSUE TITLE
CGG2015: Mexican voter sending U.S. template

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/mbc-transactional-email#31]
I voted as a user from Mexico and was sent an incorrect U.S. template:
![screen shot 2015-11-20 at 11 24 59 am](https://cloud.githubusercontent.com/assets/8696853/11305239/af9d4c8a-8f79-11e5-884c-282f6179373a.png)

@DeeZone

**Comment by DeeZone** [comment]
Try `?country_code=MX` on the voting app.
