### ISSUE TITLE
CGG2015: Brazilian voter sending U.S. template

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/mbc-transactional-email#32]
As a voter from Brazil, I was sent the incorrect transactional template:

![screen shot 2015-11-20 at 11 48 28 am](https://cloud.githubusercontent.com/assets/8696853/11305835/a81a282c-8f7c-11e5-82b1-43269c178033.png)

@DeeZone

**Comment by DeeZone** [comment]
@ArielSD Lets test this together as I'm not able to reproduce the issue. I went through the Brazilian voting process on catsgonegood.com which produce an voting conformation email using the BR template:

![image](https://cloud.githubusercontent.com/assets/2119264/11330221/5e222f6c-9175-11e5-95b4-80c9def13ffa.png)

**Comment by ArielSD** [comment]
@DeeZone You were testing on your local, right? Want to paste the other issue you created for Dave and the Voting App here and we can close this one?

**Comment by DeeZone** [comment]
Nope, this is on the cats app with all consumers on the DS servers. No local.

@DFurnes told me about the `?country_code=` parameter to force the `user_country` setting. Using this confirms all email functionality is working. One more run through by you to confirm.
